//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reservation", Namespace="http://schemas.datacontract.org/2004/07/WS.DataServices.Model")]
    public partial class Reservation : object
    {
        
        private ServiceReference1.FlightReservation FlightReservationField;
        
        private int IdField;
        
        private int NumberOfClientsField;
        
        private decimal PriceField;
        
        private ServiceReference1.DateOnly ReservationDateField;
        
        private string ReservationStatusField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.FlightReservation FlightReservation
        {
            get
            {
                return this.FlightReservationField;
            }
            set
            {
                this.FlightReservationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfClients
        {
            get
            {
                return this.NumberOfClientsField;
            }
            set
            {
                this.NumberOfClientsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.DateOnly ReservationDate
        {
            get
            {
                return this.ReservationDateField;
            }
            set
            {
                this.ReservationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservationStatus
        {
            get
            {
                return this.ReservationStatusField;
            }
            set
            {
                this.ReservationStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FlightReservation", Namespace="http://schemas.datacontract.org/2004/07/WS.DataServices.Model")]
    public partial class FlightReservation : object
    {
        
        private string AirlineField;
        
        private ServiceReference1.DateOnly DepartureDateField;
        
        private string DestinationAirportField;
        
        private ServiceReference1.DateOnly DestinationDateField;
        
        private string DpartureAirportField;
        
        private string FlightIdField;
        
        private int IdField;
        
        private decimal PriceField;
        
        private int ReservationIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Airline
        {
            get
            {
                return this.AirlineField;
            }
            set
            {
                this.AirlineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.DateOnly DepartureDate
        {
            get
            {
                return this.DepartureDateField;
            }
            set
            {
                this.DepartureDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationAirport
        {
            get
            {
                return this.DestinationAirportField;
            }
            set
            {
                this.DestinationAirportField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.DateOnly DestinationDate
        {
            get
            {
                return this.DestinationDateField;
            }
            set
            {
                this.DestinationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DpartureAirport
        {
            get
            {
                return this.DpartureAirportField;
            }
            set
            {
                this.DpartureAirportField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlightId
        {
            get
            {
                return this.FlightIdField;
            }
            set
            {
                this.FlightIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReservationID
        {
            get
            {
                return this.ReservationIDField;
            }
            set
            {
                this.ReservationIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DateOnly", Namespace="http://schemas.datacontract.org/2004/07/System")]
    public partial struct DateOnly
    {
        
        private int DayField;
        
        private int DayNumberField;
        
        private System.DayOfWeek DayOfWeekField;
        
        private int DayOfYearField;
        
        private ServiceReference1.DateOnly MaxValueField;
        
        private ServiceReference1.DateOnly MinValueField;
        
        private int MonthField;
        
        private int YearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Day
        {
            get
            {
                return this.DayField;
            }
            set
            {
                this.DayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DayNumber
        {
            get
            {
                return this.DayNumberField;
            }
            set
            {
                this.DayNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DayOfWeek DayOfWeek
        {
            get
            {
                return this.DayOfWeekField;
            }
            set
            {
                this.DayOfWeekField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DayOfYear
        {
            get
            {
                return this.DayOfYearField;
            }
            set
            {
                this.DayOfYearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.DateOnly MaxValue
        {
            get
            {
                return this.MaxValueField;
            }
            set
            {
                this.MaxValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.DateOnly MinValue
        {
            get
            {
                return this.MinValueField;
            }
            set
            {
                this.MinValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Month
        {
            get
            {
                return this.MonthField;
            }
            set
            {
                this.MonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year
        {
            get
            {
                return this.YearField;
            }
            set
            {
                this.YearField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.agencytravel/reservation/", ConfigurationName="ServiceReference1.IReservationServices")]
    public interface IReservationServices
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.agencytravel/reservation/IReservationServices/GetReservations", ReplyAction="http://ws.agencytravel/reservation/IReservationServices/GetReservationsResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Reservation[]> GetReservationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.agencytravel/reservation/IReservationServices/GetReservation", ReplyAction="http://ws.agencytravel/reservation/IReservationServices/GetReservationResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Reservation> GetReservationAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.agencytravel/reservation/IReservationServices/CreateReservation", ReplyAction="http://ws.agencytravel/reservation/IReservationServices/CreateReservationResponse" +
            "")]
        System.Threading.Tasks.Task CreateReservationAsync(ServiceReference1.Reservation reservation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.agencytravel/reservation/IReservationServices/UpdateReservation", ReplyAction="http://ws.agencytravel/reservation/IReservationServices/UpdateReservationResponse" +
            "")]
        System.Threading.Tasks.Task UpdateReservationAsync(ServiceReference1.Reservation reservation);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IReservationServicesChannel : ServiceReference1.IReservationServices, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ReservationServicesClient : System.ServiceModel.ClientBase<ServiceReference1.IReservationServices>, ServiceReference1.IReservationServices
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ReservationServicesClient() : 
                base(ReservationServicesClient.GetDefaultBinding(), ReservationServicesClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IReservationServices.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReservationServicesClient(EndpointConfiguration endpointConfiguration) : 
                base(ReservationServicesClient.GetBindingForEndpoint(endpointConfiguration), ReservationServicesClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReservationServicesClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ReservationServicesClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReservationServicesClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ReservationServicesClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReservationServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Reservation[]> GetReservationsAsync()
        {
            return base.Channel.GetReservationsAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Reservation> GetReservationAsync(int id)
        {
            return base.Channel.GetReservationAsync(id);
        }
        
        public System.Threading.Tasks.Task CreateReservationAsync(ServiceReference1.Reservation reservation)
        {
            return base.Channel.CreateReservationAsync(reservation);
        }
        
        public System.Threading.Tasks.Task UpdateReservationAsync(ServiceReference1.Reservation reservation)
        {
            return base.Channel.UpdateReservationAsync(reservation);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IReservationServices))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IReservationServices))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:9090/ReservationServices.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ReservationServicesClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IReservationServices);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ReservationServicesClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IReservationServices);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IReservationServices,
        }
    }
}
